DATA:
        ROOT: './xclip/data/countix/train'
        TRAIN_FILE: './xclip/data/countix/train/train.csv'
        VAL_FILE: '/xclip/data/countix/test/val.txt'
        DATASET: countix
        NUM_FRAMES: 64
        NUM_CLASSES: 5
        LABEL_LIST: '/xclip/data/labels.csv'
MODEL:
        ARCH: ViT-B/16
TRAIN:
        BATCH_SIZE: 5
        ACCUMULATION_STEPS: 2
        EPOCHS: 50
        LR: 2.e-6
SAVE_FREQ: 10